### ISSUE TITLE
[Bug] Splash thread Exception

### ISSUE THREAD

**Issue by b1n4ryj4n** [Fix3dll/SkyblockAddons#39]
### Bug Description

Hello,

i've been puzzled by the behavior of my splash screen. It doesn't display the typical Forge splash screen. To investigate, I conducted a fresh installation, beginning with Minecraft 1.8.9 and Forge, which went smoothly. However, when attempting to integrate your version of SBA, the game crashes during the initial boot, with no other mods present in this clean installation.

Interestingly, upon removing only the SBA mod and reintroducing all my other mods, such as Skyhanni, the game operates as expected.

### SBA Version

SkyblockAddons-1.9.0-beta.6+278-for-MC-1.8.9

### Other Installed Mods

None

### Operating System

Windows 10

### Crash Report

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_412-412, OpenLogic-OpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), OpenLogic-OpenJDK
	Memory: 3167570952 bytes (3020 MB) / 4116185088 bytes (3925 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx8192m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.9.0-beta.6+278-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.asm.SkyblockAddonsASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 552.22' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
[00:18:29] [Client thread/INFO] [FML]: MinecraftForge v11.15.1.2318 Initialized
[00:18:29] [Client thread/INFO] [FML]: Replaced 229 ore recipies
[00:18:29] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[00:18:29] [Client thread/INFO] [FML]: Searching C:\Users\B1N4RYJ4N\AppData\Roaming\PrismLauncher\instances\1.8.9\.minecraft\mods for mods
[00:18:30] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[00:18:30] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, sbaunofficial] at CLIENT
[00:18:30] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, sbaunofficial] at SERVER
[00:18:31] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SkyblockAddons Unofficial
[00:18:31] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[00:18:31] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[00:18:31] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[00:18:31] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[00:18:31] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[00:18:31] [Forge Version Check/INFO] [ForgeVersionCheck]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[00:18:31] [Client thread/INFO] [FML]: Applying holder lookups
[00:18:31] [Client thread/INFO] [FML]: Holder lookups applied
[00:18:31] [Client thread/INFO] [FML]: Injecting itemstacks
[00:18:31] [Client thread/INFO] [FML]: Itemstack injection complete
[00:18:31] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:18:31] [Thread-9/INFO]: Initializing LWJGL OpenAL
[00:18:31] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[00:18:31] [Thread-9/INFO]: OpenAL initialized.
[00:18:32] [Sound Library Loader/INFO]: Sound engine started
[00:18:32] [Client thread/INFO] [FML]: Max texture size: 16384
[00:18:32] [Client thread/INFO]: Created: 16x16 textures-atlas
[00:18:32] [Client thread/INFO] [SkyblockAddons/SkyblockAddonsASMTransformer]: [SkyblockAddons/SkyblockAddonsASMTransformer] Applying transformer codes.biscuit.skyblockaddons.asm.transformer.RenderGlobalTransformer on net.minecraft.client.renderer.RenderGlobal
[00:18:32] [Client thread/INFO] [codes.biscuit.skyblockaddons.misc.Updater]: [SkyblockAddons/Updater] Checking to see if an update is available...
[00:18:32] [Client thread/WARN] [codes.biscuit.skyblockaddons.misc.Updater]: [SkyblockAddons/Updater] The current version is newer than the latest version. Please tell an SBA developer to update the online data.
[00:18:32] [Client thread/INFO] [FML]: Injecting itemstacks
[00:18:32] [Client thread/INFO] [FML]: Itemstack injection complete
[00:18:32] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[00:18:32] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SkyblockAddons Unofficial
[00:18:32] [Thread-7/ERROR] [FML]: Splash thread Exception
java.lang.NullPointerException
	at codes.biscuit.skyblockaddons.mixins.hooks.FontRendererHook.beginRenderString(FontRendererHook.java:81) ~[FontRendererHook.class:1.9.0-beta.6+278]
	at net.minecraft.client.gui.FontRenderer.handler$beginRenderString$zzg000(FontRenderer.java:998) ~[avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java) ~[avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:525) ~[avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:286) ~[avn.class:?]
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270) ~[avn.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414) ~[SplashProgress$3.class:?]
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327) ~[SplashProgress$3.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412-412]
[00:18:32] [Client thread/INFO]: SoundSystem shutting down...
[00:18:33] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[00:18:33] [Sound Library Loader/INFO]: Starting up SoundSystem...
[00:18:33] [Thread-11/INFO]: Initializing LWJGL OpenAL
[00:18:33] [Thread-11/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[00:18:33] [Thread-11/INFO]: OpenAL initialized.
[00:18:33] [Client thread/INFO] [FML]: Max texture size: 16384
[00:18:33] [Client thread/INFO]: Created: 512x512 textures-atlas
[00:18:33] [Sound Library Loader/INFO]: Sound engine started
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: java.lang.IllegalStateException: Splash thread
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:516)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:571)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[00:18:33] [Client thread/INFO] [STDERR]: [net.minecraftforge.fml.client.SplashProgress:finish:582]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NullPointerException
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at codes.biscuit.skyblockaddons.mixins.hooks.FontRendererHook.beginRenderString(FontRendererHook.java:81)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.gui.FontRenderer.handler$beginRenderString$zzg000(FontRenderer.java:998)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:525)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:286)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327)
[00:18:33] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.Thread.run(Thread.java:750)
[00:18:33] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.9.0-beta.6+278-for-MC-1.8.9.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/1/24 12:18 AM
Description: Initializing game

SplashProgress has detected a error loading Minecraft.
This can sometimes be caused by bad video drivers.
We have automatically disabeled the new Splash Screen in config/splash.properties.
Try reloading minecraft before reporting any errors.
net.minecraftforge.fml.client.SplashProgress$5: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.disableSplash(SplashProgress.java:591)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:583)
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:408)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalStateException: Splash thread
	at net.minecraftforge.fml.client.SplashProgress.checkThreadState(SplashProgress.java:516)
	at net.minecraftforge.fml.client.SplashProgress.finish(SplashProgress.java:571)
	... 13 more
Caused by: java.lang.NullPointerException
	at codes.biscuit.skyblockaddons.mixins.hooks.FontRendererHook.beginRenderString(FontRendererHook.java:81)
	at net.minecraft.client.gui.FontRenderer.handler$beginRenderString$zzg000(FontRenderer.java:998)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java)
	at net.minecraft.client.gui.FontRenderer.func_180455_b(FontRenderer.java:525)
	at net.minecraft.client.gui.FontRenderer.func_175065_a(FontRenderer.java:286)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:270)
	at net.minecraftforge.fml.client.SplashProgress$3.drawBar(SplashProgress.java:414)
	at net.minecraftforge.fml.client.SplashProgress$3.run(SplashProgress.java:327)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Fix3dll** [comment]
@b1n4ryj4n I need more information. Are you using any other mod launcher or modified client? beginRenderString() have modInitalized and isOnSkyblock check. How could it be NPE?

**Comment by b1n4ryj4n** [comment]
It's mainly the Minecraft Launcher MultiMC5 or Prism Launcher.

![Screenshot 2024-05-01 014210](https://github.com/Fix3dll/SkyblockAddons/assets/3122325/be9b4345-e2b7-4021-ae53-ce6b351df697)

its just your mod in the folder (i dont know what you mean with NPE) all other mods working fine

![Screenshot 2024-05-01 014435](https://github.com/Fix3dll/SkyblockAddons/assets/3122325/566fd185-2e8b-456d-bd49-9d2533968a4f)

**Comment by Fix3dll** [comment]
@b1n4ryj4n Its probably related to FML. Instead of other things i fixed it with simple hacky way. Thanks for reporting.

**Comment by Fix3dll** [comment]
@b1n4ryj4n latest build should fix it but i need to do some investigation for better solution. Thanks.

**Comment by b1n4ryj4n** [comment]
Now it starts, but also it is now incompatible with Patcher (Patcher-1.8.9).

**Comment by Fix3dll** [comment]
@b1n4ryj4n completed with latest build 👍

**Comment by b1n4ryj4n** [comment]
Good Job! The newest build works for me too :D
