### ISSUE TITLE
Game crashes every time pet menu is opened

### ISSUE THREAD

**Issue by Jakub-pm** [Fix3dll/SkyblockAddons#46]
### Bug Description

As soon as the pet menu is opened, the game crashes (As seen below.)
This happened right after I updated Skyblock add-ons.

https://github.com/Fix3dll/SkyblockAddons/assets/173501679/3e7180e8-9d78-4eab-9871-30160694f52c

### SBA Version

SkyblockAddons-1.9.0-beta.11.1+315-for-MC-1.8.9.jar

### Other Installed Mods

```md
# Mods Loaded
[Minecraft Coder Pack][minecraft.jar (9.19)]
[Forge Mod Loader][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (8.0.99.99)]
[Minecraft Forge][forge-1.8.9-11.15.1.2318-1.8.9-universal.jar (11.15.1.2318)]
[Essential][Essential (forge_1.8.9).processed.jar (1.3.2.7+g7245995b31)]
[3dSkinLayers][3dSkinLayers-forge-mc1.8.9-1.2.0.jar (1.2.0)]
[OneConfig][OneConfig (1.8.9-forge).jar (0.2.2-alpha208)]
[Arrow Path][ArrowPath-v1.0.jar (1.0)]
[AutoGG][AutoGG-4.1.3 (1.8.9).jar (LOCAL)]
[Autotip][Autotip-3.1.1 (1.8.9_forge).jar (3.1.1)]
[Chatting][Chatting-1.8.9-forge-1.5.3.jar (1.5.3)]
[Craftify][Craftify-1.8.9-1.16.0-forge.jar (1.16.0)]
[CrashPatch][CrashPatch-1.8.9-forge-2.0.0.jar (2.0.0)]
[Dungeon Rooms Mod][Dungeon_Rooms-3.4.1.jar (3.4.1)]
[EvergreenHUD][EvergreenHUD-1.8.9-forge-2.1.5.jar (2.1.5)]
[Fancy Warp Menu][FancyWarpMenu-2.0-beta.1+121.jar (2.0-beta.1+121)]
[Hypixel Autocomplete Mod][Hypixel Autocomplete-1.1 (1.8.9).jar (LOCAL)]
[Hytils Reborn][Hytils Reborn-1.8.9-forge-1.6.1.jar (1.6.1)]
[Insomnia][Insomnia-1.0-REL.jar (1.0-REL)]
[Keystrokes][Keystrokes-1.8.9-forge-1.0.0.jar (1.0.0)]
[Danker's Skyblock Mod][MC.1.8.9.Danker.s.Skyblock.Mod.-.2.2.jar (2.2)]
[Mixmetica][Mixmetica-1.8.9-forge-2.0.4.jar (2.0.4)]
[NotEnoughUpdates][NotEnoughUpdates-2.3.0.jar (2.3.0+32ee0a75)]
[Optibye][Optibye-1.0.0-dep.jar (1.0.0)]
[OverflowAnimations][OverflowAnimations-1.8.9-forge-2.1.1.jar (2.1.1)]
[Patcher][Patcher-1.8.9 (1.8.9).jar (1.8.9)]
[PolySprint][PolySprint-1.8.9-forge-1.0.0.jar (1.0.0)]
[Popup Events][Popup Events-1.3.2 (1.8.9).jar (LOCAL)]
[Potion Effects][Potion_Effects_1.8.9-forge_1.0.jar (1.0-beta-2)]
[REDACTION][REDACTION-1.8.9-forge-1.3.7.jar (1.3.7)]
[Report Plus][ReportPlus-1.0.0.jar (1.0.0)]
[Resource Pack Manager][Resource_Pack_Manager_1.2.jar (1.2)]
[Gravy's Reward Claim][RewardClaim-1.0.5.jar (1.0.5)]
[Scrollable Tooltips][Scrollable Tooltips-1.4 (1.8.9).jar (LOCAL)]
[SkyblockAddons Unofficial][SkyblockAddons-1.9.0-beta.11.1+315-for-MC-1.8.9.jar (1.9.0-beta.11.1+315)]
[Skyblock Hud][SkyblockHud-Reborn-1.17.1.jar (1.17.1)]
[SkyClient Updater][SkyClient-Updater-1.8.9-forge-1.3.5.jar (1.3.5)]
[SkyClientCosmetics][SkyClientCosmetics-1.8.9-forge-1.1.16.jar (1.1.16)]
[SkyGuide][SkyGuide (1.8.9-forge)-1.3.0+oneconfig.jar (1.3.0+oneconfig)]
[Skytils][Skytils-1.10.0-pre9.jar (1.10.0-pre9)]
[Smooth Scrolling Everywhere][smooth-scrolling-everywhere-1.2.jar (1.2)]
[TNT Time][TNT Time-1.1 (1.8.9).jar (LOCAL)]
[VanillaHUD][VanillaHUD-1.8.9-forge-2.2.3.jar (2.2.3)]
```

### Operating System

Windows 10

### Crash Report

---- Minecraft Crash Report ----
***Skytils detected Mixins in this crash***
Mixin registrant mixin.crashpatch.json, class org.polyfrost.crashpatch.mixin.MixinMinecraft, transformed net.minecraft.client.Minecraft.handler$zpk000$run

WARNING: coremods are present:
  FMLLoadingPlugin (TNT Time-1.1 (1.8.9).jar)
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  ModDetectorPlugin (OverflowAnimations-1.8.9-forge-2.1.1.jar)
  ModsCheckerPlugin (CrashPatch-1.8.9-forge-2.0.0.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.9.0-beta.11.1+315-for-MC-1.8.9.jar)
  ModTweaker (Patcher-1.8.9 (1.8.9).jar)
  PatcherTweaker (Patcher-1.8.9 (1.8.9).jar)
  Skytils On Top (Skytils-1.10.0-pre9.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 6/21/24 2:54 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at codes.biscuit.skyblockaddons.utils.pojo.PetInfo.equals(PetInfo.java:45)
	at codes.biscuit.skyblockaddons.features.PetManager.checkCurrentPet(PetManager.java:80)
	at codes.biscuit.skyblockaddons.listeners.PlayerListener.onTick(PlayerListener.java:653)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_658_PlayerListener_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1624)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.handler$zpk000$run(Minecraft.java:3250)
	at net.minecraft.client.Minecraft.run(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codes.biscuit.skyblockaddons.utils.pojo.PetInfo.equals(PetInfo.java:45)
	at codes.biscuit.skyblockaddons.features.PetManager.checkCurrentPet(PetManager.java:80)
	at codes.biscuit.skyblockaddons.listeners.PlayerListener.onTick(PlayerListener.java:653)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_658_PlayerListener_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)

-- Affected level --
Details:
	Level name: MpServer
	All players: 3 total; [EntityPlayerSP['JaynixUWU'/6327695, l='MpServer', x=7.50, y=100.00, z=7.50], EntityOtherPlayerMP['Darth_Nihil_1337'/6327696, l='MpServer', x=7.50, y=112.98, z=7.50], EntityOtherPlayerMP['§bSam '/6327904, l='MpServer', x=4.50, y=85.00, z=4.50]]
	Chunk stats: MultiplayerChunkCache: 225, 225
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 7.00,100.00,7.00 - World: (7,100,7), Chunk: (at 7,6,7 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 88 game time, 16890 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 84 total; [EntityArmorStand['Armor Stand'/6327648, l='MpServer', x=2.63, y=-0.47, z=12.75], EntityOtherPlayerMP['§bSam '/6327904, l='MpServer', x=4.50, y=85.00, z=4.50], EntityArmorStand['Armor Stand'/6327649, l='MpServer', x=1.56, y=1.28, z=11.63], EntityArmorStand['§bSam'/6327905, l='MpServer', x=4.50, y=85.00, z=4.50], EntityArmorStand['Armor Stand'/6327650, l='MpServer', x=1.94, y=0.09, z=12.75], EntityArmorStand['§e§lCLICK'/6327906, l='MpServer', x=4.50, y=84.75, z=4.50], EntityArmorStand['Armor Stand'/6327651, l='MpServer', x=2.25, y=0.09, z=12.19], EntityArmorStand['Armor Stand'/6327652, l='MpServer', x=2.25, y=0.09, z=13.13], EntityArmorStand['Armor Stand'/6327653, l='MpServer', x=2.81, y=0.09, z=12.75], EntityArmorStand['Armor Stand'/6327654, l='MpServer', x=2.47, y=0.91, z=12.03], EntityArmorStand['Armor Stand'/6327655, l='MpServer', x=2.47, y=0.91, z=12.94], EntityArmorStand['Armor Stand'/6327656, l='MpServer', x=2.28, y=-0.22, z=12.75], EntityArmorStand['Armor Stand'/6327657, l='MpServer', x=1.56, y=1.28, z=12.53], EntityArmorStand['Armor Stand'/6327658, l='MpServer', x=3.66, y=0.81, z=13.59], EntityArmorStand['Armor Stand'/6327659, l='MpServer', x=2.47, y=0.38, z=13.94], EntityArmorStand['Armor Stand'/6327660, l='MpServer', x=2.38, y=0.38, z=11.56], EntityArmorStand['Armor Stand'/6327661, l='MpServer', x=2.69, y=0.38, z=11.69], EntityArmorStand['Armor Stand'/6327662, l='MpServer', x=2.91, y=0.00, z=11.47], EntityArmorStand['Armor Stand'/6327663, l='MpServer', x=2.38, y=0.00, z=11.28], EntityArmorStand['Armor Stand'/6327664, l='MpServer', x=2.78, y=0.28, z=13.81], EntityArmorStand['Armor Stand'/6327665, l='MpServer', x=3.06, y=0.00, z=14.09], EntityArmorStand['Armor Stand'/6327666, l='MpServer', x=2.47, y=0.00, z=14.31], EntityArmorStand['Armor Stand'/6327667, l='MpServer', x=3.66, y=0.81, z=11.59], EntityArmorStand['Armor Stand'/6327668, l='MpServer', x=2.09, y=1.00, z=11.66], EntityArmorStand['Armor Stand'/6327669, l='MpServer', x=2.22, y=1.00, z=11.19], EntityArmorStand['Armor Stand'/6327670, l='MpServer', x=2.34, y=1.00, z=11.81], EntityArmorStand['Armor Stand'/6327671, l='MpServer', x=2.09, y=0.84, z=13.81], EntityArmorStand['Armor Stand'/6327672, l='MpServer', x=2.47, y=1.03, z=13.09], EntityArmorStand['Armor Stand'/6327673, l='MpServer', x=1.88, y=0.63, z=12.31], EntityArmorStand['Armor Stand'/6327674, l='MpServer', x=1.88, y=0.63, z=13.19], EntityArmorStand['Armor Stand'/6327675, l='MpServer', x=26.50, y=1.00, z=22.50], EntityCow['Cow'/6327676, l='MpServer', x=27.50, y=1.00, z=24.50], EntityCow['Cow'/6327677, l='MpServer', x=27.69, y=1.00, z=24.53], EntityCow['Cow'/6327678, l='MpServer', x=26.58, y=1.00, z=21.84], EntityCow['Cow'/6327679, l='MpServer', x=27.50, y=1.00, z=24.50], EntityVillager['Villager'/6327619, l='MpServer', x=10.50, y=85.00, z=3.50], EntityArmorStand['Armor Stand'/6327625, l='MpServer', x=20.50, y=1.00, z=22.50], EntityCow['Cow'/6327626, l='MpServer', x=20.50, y=1.00, z=22.50], EntityOtherPlayerMP['Darth_Nihil_1337'/6327696, l='MpServer', x=7.50, y=112.98, z=7.50], EntityCow['Cow'/6327627, l='MpServer', x=20.50, y=1.00, z=22.50], EntityCow['Cow'/6327628, l='MpServer', x=19.09, y=1.00, z=20.50], EntityCow['Cow'/6327629, l='MpServer', x=20.50, y=1.00, z=22.50], EntityCow['Cow'/6327630, l='MpServer', x=20.50, y=1.00, z=22.50], EntityArmorStand['Armor Stand'/6327631, l='MpServer', x=20.50, y=1.00, z=27.50], EntityArmorStand['Armor Stand'/6327632, l='MpServer', x=9.50, y=1.00, z=26.50], EntitySlime['Slime'/6327633, l='MpServer', x=9.31, y=1.00, z=28.38], EntitySlime['Slime'/6327634, l='MpServer', x=8.47, y=1.00, z=28.09], EntitySlime['Slime'/6327635, l='MpServer', x=8.22, y=1.00, z=27.78], EntityOtherPlayerMP['§bSam '/6327904, l='MpServer', x=4.50, y=85.00, z=4.50], EntitySlime['Slime'/6327636, l='MpServer', x=10.59, y=1.00, z=28.66], EntitySlime['Slime'/6327637, l='MpServer', x=8.50, y=1.00, z=27.78], EntityArmorStand['Armor Stand'/6327638, l='MpServer', x=20.50, y=1.00, z=37.50], EntityArmorStand['Armor Stand'/6327639, l='MpServer', x=20.50, y=1.00, z=32.50], EntityArmorStand['Armor Stand'/6327640, l='MpServer', x=25.50, y=1.00, z=32.50], EntityArmorStand['Armor Stand'/6327641, l='MpServer', x=2.94, y=0.06, z=12.78], EntityArmorStand['Armor Stand'/6327642, l='MpServer', x=2.94, y=0.06, z=12.16], EntityArmorStand['Armor Stand'/6327643, l='MpServer', x=2.94, y=0.06, z=13.41], EntityArmorStand['Armor Stand'/6327644, l='MpServer', x=2.81, y=0.06, z=11.84], EntityArmorStand['Armor Stand'/6327645, l='MpServer', x=2.81, y=0.06, z=13.72], EntityArmorStand['Armor Stand'/6327646, l='MpServer', x=2.50, y=0.06, z=13.84], EntityArmorStand['Armor Stand'/6327647, l='MpServer', x=2.50, y=0.06, z=11.72], EntityCow['Cow'/6327680, l='MpServer', x=27.50, y=1.00, z=24.50], EntityPlayerSP['JaynixUWU'/6327695, l='MpServer', x=7.50, y=100.00, z=7.50], EntityArmorStand['Armor Stand'/6327681, l='MpServer', x=25.50, y=1.00, z=37.50], EntityArmorStand['Armor Stand'/6327682, l='MpServer', x=8.50, y=2.00, z=11.50], EntityArmorStand['Armor Stand'/6327683, l='MpServer', x=20.50, y=1.00, z=16.50], EntityCow['Cow'/6327684, l='MpServer', x=19.50, y=1.00, z=16.50], EntityItem['item.item.slimeball'/6328452, l='MpServer', x=10.45, y=1.00, z=26.30], EntityCow['Cow'/6327685, l='MpServer', x=19.50, y=1.00, z=16.50], EntityItem['item.item.slimeball'/6328453, l='MpServer', x=10.50, y=1.00, z=27.80], EntityCow['Cow'/6327686, l='MpServer', x=19.50, y=1.00, z=16.50], EntityItem['item.item.slimeball'/6328454, l='MpServer', x=10.78, y=1.00, z=27.88], EntityCow['Cow'/6327687, l='MpServer', x=19.50, y=1.00, z=16.50], EntityCow['Cow'/6327688, l='MpServer', x=19.50, y=1.00, z=16.50], EntityArmorStand['Armor Stand'/6327689, l='MpServer', x=26.50, y=1.00, z=16.50], EntityCow['Cow'/6327690, l='MpServer', x=24.50, y=1.00, z=14.50], EntityCow['Cow'/6327691, l='MpServer', x=24.50, y=1.00, z=14.50], EntityCow['Cow'/6327692, l='MpServer', x=24.69, y=1.00, z=14.69], EntityCow['Cow'/6327693, l='MpServer', x=24.50, y=1.00, z=14.50], EntityArmorStand['§6§lNEW UPDATE'/6327821, l='MpServer', x=10.50, y=85.34, z=3.50], EntityCow['Cow'/6327694, l='MpServer', x=24.50, y=1.00, z=14.50], EntityArmorStand['Jerry'/6327822, l='MpServer', x=10.50, y=85.09, z=3.50], EntityArmorStand['§e§lCLICK'/6327823, l='MpServer', x=10.50, y=84.84, z=3.50], EntityOtherPlayerMP['Darth_Nihil_1337'/6327696, l='MpServer', x=7.50, y=112.98, z=7.50]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (2024.6.21.1) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:402)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.handler$zpk000$run(Minecraft.java:3261)
	at net.minecraft.client.Minecraft.run(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Game Directory: C:\Users\jayni\AppData\Roaming\PrismLauncher\instances\Skyclient\.minecraft
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2216115320 bytes (2113 MB) / 3749707776 bytes (3576 MB) up to 3749707776 bytes (3576 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2000m -Xmx4000m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M6_pre2 42 mods loaded, 42 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                          | Version             | Source                                              |
	| ------ | --------------------------- | ------------------- | --------------------------------------------------- |
	| UCHIJA | mcp                         | 9.19                | minecraft.jar                                       |
	| UCHIJA | FML                         | 8.0.99.99           | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar        |
	| UCHIJA | Forge                       | 11.15.1.2318        | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar        |
	| UCHIJA | essential                   | 1.0.0               | Essential (forge_1.8.9).processed.jar               |
	| UCHIJA | skinlayers3d                | 1.2.0               | 3dSkinLayers-forge-mc1.8.9-1.2.0.jar                |
	| UCHIJA | oneconfig                   | 0.2.2-alpha208      | OneConfig (1.8.9-forge).jar                         |
	| UCHIJA | arrowpath                   | 1.0                 | ArrowPath-v1.0.jar                                  |
	| UCHIJA | autogg                      | 4.1.3               | AutoGG-4.1.3 (1.8.9).jar                            |
	| UCHIJA | autotip                     | 3.1                 | Autotip-3.1.1 (1.8.9_forge).jar                     |
	| UCHIJA | chatting                    | 1.5.3               | Chatting-1.8.9-forge-1.5.3.jar                      |
	| UCHIJA | craftify                    | 1.16.0              | Craftify-1.8.9-1.16.0-forge.jar                     |
	| UCHIJA | crashpatch                  | 2.0.0               | CrashPatch-1.8.9-forge-2.0.0.jar                    |
	| UCHIJA | dungeonrooms                | 3.4.1               | Dungeon_Rooms-3.4.1.jar                             |
	| UCHIJA | evergreenhud                | 2.1.5               | EvergreenHUD-1.8.9-forge-2.1.5.jar                  |
	| UCHIJA | fancywarpmenu               | 2.0-beta.1+121      | FancyWarpMenu-2.0-beta.1+121.jar                    |
	| UCHIJA | hypixel_auto_complete       | 1.1.0               | Hypixel Autocomplete-1.1 (1.8.9).jar                |
	| UCHIJA | hytils-reborn               | 1.6.1               | Hytils Reborn-1.8.9-forge-1.6.1.jar                 |
	| UCHIJA | insomnia                    | 1.0-REL             | Insomnia-1.0-REL.jar                                |
	| UCHIJA | polyfrostkeystrokes         | 1.0.0               | Keystrokes-1.8.9-forge-1.0.0.jar                    |
	| UCHIJA | Danker's Skyblock Mod       | 2.2                 | MC.1.8.9.Danker.s.Skyblock.Mod.-.2.2.jar            |
	| UCHIJA | mixmetica                   | 2.0.4               | Mixmetica-1.8.9-forge-2.0.4.jar                     |
	| UCHIJA | notenoughupdates            | 2.3.0               | NotEnoughUpdates-2.3.0.jar                          |
	| UCHIJA | optibye                     | 1.0.0               | Optibye-1.0.0-dep.jar                               |
	| UCHIJA | overflowanimations          | 2.1.1               | OverflowAnimations-1.8.9-forge-2.1.1.jar            |
	| UCHIJA | patcher                     | 1.8.9               | Patcher-1.8.9 (1.8.9).jar                           |
	| UCHIJA | polysprint                  | 1.0.0               | PolySprint-1.8.9-forge-1.0.0.jar                    |
	| UCHIJA | popup_events                | 1.3.2               | Popup Events-1.3.2 (1.8.9).jar                      |
	| UCHIJA | potioneffects               | 1.0                 | Potion_Effects_1.8.9-forge_1.0.jar                  |
	| UCHIJA | redaction                   | 1.3.5               | REDACTION-1.8.9-forge-1.3.7.jar                     |
	| UCHIJA | reportplus                  | 1.0.0               | ReportPlus-1.0.0.jar                                |
	| UCHIJA | resourcepackmanager         | 1.2                 | Resource_Pack_Manager_1.2.jar                       |
	| UCHIJA | gravyrewardclaim            | 1.0.4               | RewardClaim-1.0.5.jar                               |
	| UCHIJA | text_overflow_scroll        | 1.4.0               | Scrollable Tooltips-1.4 (1.8.9).jar                 |
	| UCHIJA | sbaunofficial               | 1.9.0-beta.11.1+315 | SkyblockAddons-1.9.0-beta.11.1+315-for-MC-1.8.9.jar |
	| UCHIJA | skyblockhud                 | 1.17.1              | SkyblockHud-Reborn-1.17.1.jar                       |
	| UCHIJA | skyblockclientupdater       | @VER                | SkyClient-Updater-1.8.9-forge-1.3.5.jar             |
	| UCHIJA | skyclientcosmetics          | 1.1.16              | SkyClientCosmetics-1.8.9-forge-1.1.16.jar           |
	| UCHIJA | skyguide                    | 1.3.0+oneconfig     | SkyGuide (1.8.9-forge)-1.3.0+oneconfig.jar          |
	| UCHIJA | skytils                     | 1.10.0-pre9         | Skytils-1.10.0-pre9.jar                             |
	| UCHIJA | smooth-scrolling-everywhere | 1.2                 | smooth-scrolling-everywhere-1.2.jar                 |
	| UCHIJA | tnttime                     | 1.1.0               | TNT Time-1.1 (1.8.9).jar                            |
	| UCHIJA | vanillahud                  | 2.2.3               | VanillaHUD-1.8.9-forge-2.2.3.jar                    |

	Loaded coremods (and transformers): 
FMLLoadingPlugin (TNT Time-1.1 (1.8.9).jar)
  club.sk1er.mods.tnttimer.forge.ClassTransformer
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
ModDetectorPlugin (OverflowAnimations-1.8.9-forge-2.1.1.jar)
  
ModsCheckerPlugin (CrashPatch-1.8.9-forge-2.0.0.jar)
  
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.9.0-beta.11.1+315-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.asm.SkyblockAddonsASMTransformer
ModTweaker (Patcher-1.8.9 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
PatcherTweaker (Patcher-1.8.9 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
Skytils On Top (Skytils-1.10.0-pre9.jar)
  gg.skytils.skytilsmod.asm.SkytilsTransformer
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.25, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: FurfSky Reborn FULL [1.7.3].zip, 1.14 Packport.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	OptiFine Version: OptiFine_1.8.9_HD_U_M6_pre2
	OptiFine Build: 20211101-204933
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 536.25
	OpenGlRenderer: NVIDIA GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by Fix3dll** [comment]
@Jakub-pm could you try latest build? https://github.com/Fix3dll/SkyblockAddons/actions/runs/9624537774/artifacts/1627389409

**Comment by Jakub-pm** [comment]
Its fixed!!! Thank you!!!

**Comment by yand3r3d3v** [comment]
Don't fixed, i get this error again
