### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by TheDGOfficial** [Fix3dll/SkyblockAddons#55]
### Bug Description

Relevant errors below. Does not happen with original SBA.

```java
[00:47:48] [Client thread/INFO]: [SkyblockAddons/SkyblockAddonsASMTransformer] Applying transformer codes.biscuit.skyblockaddons.asm.transformer.RenderGlobalTransformer on net.minecraft.client.renderer.RenderGlobal
[00:47:48] [Client thread/ERROR]: Exception when transforming net.minecraft.client.renderer.RenderGlobal : NegativeArraySizeException
java.lang.NegativeArraySizeException
	at org.objectweb.asm.Frame.merge(Frame.java:1447) ~[Essential%20(forge_1.8.9).processed.jar:?]
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1516) ~[Essential%20(forge_1.8.9).processed.jar:?]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:835) ~[Essential%20(forge_1.8.9).processed.jar:?]
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727) ~[Essential%20(forge_1.8.9).processed.jar:?]
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:412) ~[Essential%20(forge_1.8.9).processed.jar:?]
	at club.sk1er.patcher.tweaker.ClassTransformer.createTransformer(ClassTransformer.java:180) [ClassTransformer.class:?]
	at club.sk1er.patcher.tweaker.ClassTransformer.transform(ClassTransformer.java:218) [ClassTransformer.class:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_422]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_422]
	at java.lang.Class.getDeclaredConstructors0(Native Method) [?:1.8.0_422]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2699) [?:1.8.0_422]
	at java.lang.Class.getConstructor0(Class.java:3103) [?:1.8.0_422]
	at java.lang.Class.getConstructor(Class.java:1853) [?:1.8.0_422]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:101) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:85) [EventBus.class:?]
	at com.chattriggers.ctjs.CTJS.preInit(CTJS.kt:86) [ctjs-2.2.1-1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417) [ave.class:?]
	at net.minecraft.client.Minecraft.handler$chh000$run(Minecraft.java:3239) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148) [stage2.forge_1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_422]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_422]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_422]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_422]
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293) [stage1.jar:8]
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44) [stage1.jar:8]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_422]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_422]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_422]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_422]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) [Autotip-3.2%20(1.8.9_forge).jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) [Autotip-3.2%20(1.8.9_forge).jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_422]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_422]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_422]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_422]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_422]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

### SBA Version

Self built from master branch to see if it still happens there, otherwise latest beta from modrinth.

### Operating System

Ubuntu 24.0.1 LTS

**Comment by Fix3dll** [comment]
@TheDGOfficial Could you share more information? Does it still crash when you try to launch the game with just SBA?

**Comment by TheDGOfficial** [comment]
Doesn't happen with just SBA, I will experiment with adding and removing mods later when I have more time to find the mod causing it although it didn't happen with original SBA with the same set of mods. I can close this issue though I guess as it works with just SBA and I already built a version commenting out the registerTransformer for the RenderGlobalTransformer and all seemed to work fine.

**Comment by Fix3dll** [comment]
@TheDGOfficial Could you try to remove `ClassWriter.COMPUTE_MAXS`?
https://github.com/Fix3dll/SkyblockAddons/blob/13f7ddfdf4960961bf728eb2d44b7406f677d19e/src/main/java/codes/biscuit/skyblockaddons/asm/SkyblockAddonsASMTransformer.java#L54
