### ISSUE TITLE
[Bug] Unable to launch game / crash before starting

### ISSUE THREAD

**Issue by Qartzin** [Fix3dll/SkyblockAddons#64]
### Bug Description

Game crashes before starting, tried older versions of the mod but it still shows same reason for crash.

### SBA Version

SkyblockAddons-1.7.2-for-MC-1.8.9.jar
SkyblockAddons-1.9.0-beta.12.1+320-for-MC-1.8.9.jar
SkyblockAddons-1.9.0-beta.14+327-for-MC-1.8.9.jar

### Other Installed Mods

Better Sprint
Chat Triggers
Controlling
Cowlection
CrashPatch
Danker's Skyblock Mod
Dulkir Mod
Dungeon Rooms
Dungeons Guide
Entity Culling
Essential Mod
Not Enough Updates
Optibye
Optifine
Patcher
Phosphor Legacy Forge
Polished Gui
Redirectionor Retro
Resource Pack Organizer
Scrollable Tooltips
Server Redirect
Skyblock Tweaks
Skyblock Addons Unofficial
Skytils
Velox Caelo
Desco1 Water Solver

### Operating System

Windows 11

### Crash Report

---- Minecraft Crash Report ----
***Skytils detected Mixins in this crash***
Mixin registrant mixin.crashpatch.json, class org.polyfrost.crashpatch.mixin.MixinMinecraft, transformed net.minecraft.client.Minecraft.handler$bme000$run

WARNING: coremods are present:
  FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  AsmHelperLoadingPlugin (ctjs-2.2.1-1.8.9.jar)
  PhosphorFMLPlugin (phosphor-universal.jar)
  SkyblockAddonsLoadingPlugin (SkyblockAddons-1.9.0-beta.16+366-for-MC-1.8.9.jar)
  Skytils On Top (Skytils-1.10.6.jar)
  redirectionor (redirectionor-1.4 for 1.12.2-1.8.8.jar)
  PatcherTweaker (Patcher-1.8.7 (1.8.9).jar)
  DGTweaker (dungeonsguide-4.0.0-beta11.0-standalone.jar)
  ModTweaker (Patcher-1.8.7 (1.8.9).jar)
  PolishedGUI (Polished-GUI-1.0.0.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/15/24 10:36 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at codes.biscuit.skyblockaddons.features.FetchurManager.hasFetchedToday(FetchurManager.java:82)
	at codes.biscuit.skyblockaddons.features.FetchurManager.postPersistentConfigLoad(FetchurManager.java:129)
	at codes.biscuit.skyblockaddons.config.PersistentValuesManager.loadValues(PersistentValuesManager.java:73)
	at codes.biscuit.skyblockaddons.SkyblockAddons.preInit(SkyblockAddons.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
	at net.minecraft.client.Minecraft.handler$bme000$run(Minecraft.java:3239)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codes.biscuit.skyblockaddons.features.FetchurManager.hasFetchedToday(FetchurManager.java:82)
	at codes.biscuit.skyblockaddons.features.FetchurManager.postPersistentConfigLoad(FetchurManager.java:129)
	at codes.biscuit.skyblockaddons.config.PersistentValuesManager.loadValues(PersistentValuesManager.java:73)
	at codes.biscuit.skyblockaddons.SkyblockAddons.preInit(SkyblockAddons.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.handler$bme000$run(Minecraft.java:3239)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:220)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:116)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Game Directory: C:\user\Stuff\ATLauncher\instances\Hypixel189withForge
	ChatTriggers modules: [Module{name=axios,version=1.0.9}, Module{name=BeaconBeam,version=1.0.1}, Module{name=BetterMap,version=1.2.1}, Module{name=Bloom,version=4.8.4}, Module{name=BloomCore,version=0.4.15}, Module{name=Coleweight,version=1.13.5}, Module{name=Elementa,version=1.5.2}, Module{name=guimanager,version=0.1.7}, Module{name=NwjnAddons,version=0.11.5}, Module{name=PogData,version=1.0.3}, Module{name=PromiseV2,version=1.0.4}, Module{name=RenderLib,version=0.4.0}, Module{name=requestV2,version=2.1.1}, Module{name=Rift,version=0.0.6}, Module{name=soopyAddonsData,version=0.0.1}, Module{name=soopyApis,version=0.1.17}, Module{name=SoopyV2,version=2.1.202}, Module{name=Vigilance,version=1.3.2}]
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 375740808 bytes (358 MB) / 1308622848 bytes (1248 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version              | Source                                            |
	| ----- | --------------------- | -------------------- | ------------------------------------------------- |
	| UCH   | mcp                   | 9.19                 | minecraft.jar                                     |
	| UCH   | FML                   | **.**.**.**            | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar      |
	| UCH   | Forge                 | 11.15.1.2318         | forge-1.8.9-11.15.1.2318-1.8.9-universal.jar      |
	| UCH   | dungeons_guide        | Not Loaded           | minecraft.jar                                     |
	| UCH   | redirectionor         | 1.4 for 1.12.2-1.8.8 | minecraft.jar                                     |
	| UCH   | essential             | 1.0.0                | Essential (forge_1.8.9).processed.jar             |
	| UCH   | oneconfig             | 0.2.2-alpha213       | OneConfig (1.8.9-forge).jar                       |
	| UCH   | entityculling         | 1.5.0                | entityculling-forge-mc1.8.9-1.5.0.jar             |
	| UCH   | hypixel_mod_api       | 1.0.1.1              | HypixelModAPI-1.0.1.1.jar                         |
	| UCH   | bettersprint          | 1.0.0                | BetterSprint-1.0.0.jar                            |
	| UCH   | controlling           | 7.0.0                | Controlling-7.0.0.1.jar                           |
	| UCH   | cowlection            | 1.8.9-0.16.1         | Cowlection-1.8.9-0.16.1.jar                       |
	| UCH   | crashpatch            | 2.0.1                | CrashPatch-1.8.9-forge-2.0.1.jar                  |
	| UCH   | chattriggers          | 2.2.1                | ctjs-2.2.1-1.8.9.jar                              |
	| UCH   | dulkirmod             | 1.2.8                | DulkirMod-1.2.8.jar                               |
	| UCH   | dungeonrooms          | 3.4.1                | Dungeon_Rooms-3.4.1.jar                           |
	| UCH   | dungeons_guide_loader | 4.0.0                | dungeonsguide-4.0.0-beta11.0-standalone.jar       |
	| UCH   | Danker's Skyblock Mod | 2.3.1                | MC.1.8.9.Danker.s.Skyblock.Mod.-.2.3.1.jar        |
	| UCH   | notenoughupdates      | 2.3.3                | NotEnoughUpdates-2.3.3.jar                        |
	| UCH   | optibye               | 1.0.0                | Optibye-1.0.0-dep.jar                             |
	| UCH   | patcher               | 1.8.7                | Patcher-1.8.7 (1.8.9).jar                         |
	| UCH   | phosphor-lighting     | **.**.**.**              | phosphor-universal.jar                            |
	| UCH   | polishedgui           | 1.0.0                | Polished-GUI-1.0.0.jar                            |
	| UCH   | ResourcePackOrganizer | 1.0.3                | ResourcePackOrganizer  MC-1.8.9  v1.0.3.jar       |
	| UCH   | text_overflow_scroll  | 1.4.0                | Scrollable Tooltips-1.4 (1.8.9).jar               |
	| UCH   | serverredirect        | 1.4.5                | ServerRedirect-ForgeMC8-1.4.5.jar                 |
	| UCE   | sbaunofficial         | 1.9.0-beta.16+366    | SkyblockAddons-1.9.0-beta.16+366-for-MC-1.8.9.jar |
	| UCH   | skyblocktweaks        | 1.0.1-BETA4          | SkyblockTweaks-1.0.1-BETA4.jar                    |
	| UCH   | skyhanni              | 0.26                 | SkyHanni-0.26.jar                                 |
	| UCH   | skytils               | 1.10.6               | Skytils-1.10.6.jar                                |
	| UCH   | soopyv2forge          | 1.1                  | soopyv2forge-1.1.jar                              |
	| UCH   | veloxcaelo            | 1.0.2                | veloxcaelo-1.1.0.jar                              |
	| UCH   | somewatersolver       | 1.1.2                | WaterSolver.jar                                   |

	Loaded coremods (and transformers): 
FMLLoadingPlugin (Scrollable Tooltips-1.4 (1.8.9).jar)
  club.sk1er.mods.scrollabletooltips.forge.ClassTransformer
AsmHelperLoadingPlugin (ctjs-2.2.1-1.8.9.jar)
  com.chattriggers.ctjs.launch.plugin.CTJSTransformer
PhosphorFMLPlugin (phosphor-universal.jar)
  
SkyblockAddonsLoadingPlugin (SkyblockAddons-1.9.0-beta.16+366-for-MC-1.8.9.jar)
  codes.biscuit.skyblockaddons.asm.SkyblockAddonsASMTransformer
Skytils On Top (Skytils-1.10.6.jar)
  gg.skytils.skytilsmod.asm.SkytilsTransformer
redirectionor (redirectionor-1.4 for 1.12.2-1.8.8.jar)
  com.Hileb.teampotato.redirectionor.RedirectionorTransformer
PatcherTweaker (Patcher-1.8.7 (1.8.9).jar)
  club.sk1er.patcher.tweaker.ClassTransformer
DGTweaker (dungeonsguide-4.0.0-beta11.0-standalone.jar)
  kr.syeyoung.dungeonsguide.launcher.coremod.EventBusTransformer
ModTweaker (Patcher-1.8.7 (1.8.9).jar)
  club.sk1er.patcher.tweaker.other.ModClassTransformer
PolishedGUI (Polished-GUI-1.0.0.jar)
  
	Skytils Debug Info: {HasBetterFPS=false, BetterFPS Version=NONE, Disabled Start Checks=false}
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 7800 XT GL version 4.6.0 Compatibility Profile Context 24.8.1.240822, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 7600 6-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: 20210124-163719
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 24.8.1.240822
	OpenGlRenderer: AMD Radeon RX 7800 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by Qartzin** [comment]
Deleting my Config folder and Oneconfig config folder fixed crashes for me, 
Just imported back some configs i wanted to keep:
Skytils 
NEU 
Dulkir
Danker
Dungeon Guide
Dungeon Rooms
SImple Toggle Sprint
patcher
Skyblock Addons Unofficial

**Comment by Fix3dll** [comment]
@Qartzin Did you experience this problem when you first switched to the unofficial version or were you using it before?

**Comment by Qartzin** [comment]
I have been using Sb Addons Unofficial  for a while now.  It started crashing today.
Yesterday though i had problem with my settings resseting after i closed game and opened it too fast and often after installing and checking other mods.

**Comment by Fix3dll** [comment]
Fixed in 1.9.0-beta.16. If it happens again, you can reopen the issue.
